# -*- coding: utf-8 -*-
"""mess service code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_gOQhmlh8ejrvDLlCWLSA2lvbgLqJmI
"""

import pandas as pd
import matplotlib.pyplot as plt

data = {
    "Day": ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
    "Total_Students": [500,500,500,500,500,500,500],
    "Attendance_Percentage": [85,78,92,70,88,55,40],
    "Students_Present": [425,390,460,350,440,275,200],
    "Mess_Usage_Percentage": [80,75,90,65,85,50,35],
    "Meals_Consumed": [400,370,455,340,430,260,190],
    "Wastage_Level": ["Low","Low","Very Low","Medium","Low","High","Very High"]
}

df = pd.DataFrame(data)
print(df)

print("\n📊 Summary Statistics:")
print(df.describe())

correlation = df["Attendance_Percentage"].corr(df["Mess_Usage_Percentage"])
print("\n🔗 Correlation between Attendance and Mess Usage:", correlation)

max_usage = df.loc[df["Mess_Usage_Percentage"].idxmax()]
min_usage = df.loc[df["Mess_Usage_Percentage"].idxmin()]

print("\n🔥 Highest Mess Usage Day:")
print(max_usage)

print("\n❄ Lowest Mess Usage Day:")
print(min_usage)

high_waste_days = df[df["Wastage_Level"].isin(["High", "Very High"])]
print("\n⚠ High Waste Days:")
print(high_waste_days)

df["Efficiency"] = df["Meals_Consumed"] / df["Students_Present"]
print("\n📈 Efficiency Column Added:")
print(df[["Day", "Efficiency"]])

"""8"""

plt.figure(figsize=(10,5))

plt.plot(df["Day"], df["Attendance_Percentage"], marker="o", label="Attendance %")
plt.plot(df["Day"], df["Mess_Usage_Percentage"], marker="o", label="Mess Usage %")

plt.title("Attendance vs Mess Usage Trend")
plt.xlabel("Day")
plt.ylabel("Percentage")
plt.legend()
plt.grid()
plt.show()

"""9 prediction

"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Dataset
data = {
    "Attendance_Percentage": [85,78,92,70,88,55,40],
    "Mess_Usage_Percentage": [80,75,90,65,85,50,35],
    "Meals_Consumed": [400,370,455,340,430,260,190]
}

df = pd.DataFrame(data)

# Feature & Target
X = df[["Attendance_Percentage"]]
y = df["Meals_Consumed"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction function
def predict_meals(attendance_percent):
    prediction = model.predict([[attendance_percent]])
    return int(prediction[0])

# Example: Predict next day demand
next_day_attendance = 82
predicted_meals = predict_meals(next_day_attendance)

print("Predicted Meals Demand:", predicted_meals)























